config/routes.rb
Contactocoaching::Application.routes.draw do

  scope '(:locale)', :locale => /#{I18n.available_locales.join("|")}/ do

    resources :videos
    resources :clients do
      resources :photos
    end
    resources :addresses
    resources :whoweares
    resources :howdowedos
    resources :teams
    resources :whatdowedos
    resources :contacts

    match 'quienes_somos' => 'whoweares#index'
    match "equipo" => "teams#index"
    match 'clientes' => 'clients#index'
    match 'videos' => 'videos#index'
    match 'como_lo_hacemos' => 'howdowedos#index'
    match 'que_hacemos' => 'whatdowedos#index'
    match 'contacto' => 'addresses#index'

    match "/admin" =>'access#index'
    match "/cms" =>'access#index'
    match "/login" =>'access#login'
    match "/attempt_login" =>'access#attempt_login'
    match "/logout" =>'access#logout'

    root :to => "home#index"

  end

end

app/models/address.rb
class Address < ActiveRecord::Base
  translates :title, :description
end

app/models/admin_user.rb
require 'digest/sha1'
class AdminUser < ActiveRecord::Base
  
  attr_accessor :password
  
  EMAIL_REGEX = /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}$/i
  
  # new "sexy" validations
  validates :first_name, :presence => true, :length => { :maximum => 25 }
  validates :last_name, :presence => true, :length => { :maximum => 50 }
  validates :username, :length => { :within => 8..25 }, :uniqueness => true
  validates :email, :presence => true, :length => { :maximum => 100 }, 
    :format => EMAIL_REGEX, :confirmation => true

  # only on create, so other attributes of this user can be changed
  validates_length_of :password, :within => 8..25, :on => :create

  before_save :create_hashed_password
  after_save :clear_password

  scope :named, lambda {|first,last| where(:first_name => first, :last_name => last)}
  scope :sorted, order("admin_users.last_name ASC, admin_users.first_name ASC")
  
  attr_protected :hashed_password, :salt
  
  def name
    "#{first_name} #{last_name}"
  end
  
  def self.authenticate(username="", password="")
    user = AdminUser.find_by_username(username)
    if user && user.password_match?(password)
      return user
    else
      return false
    end
  end

  # The same password string with the same hash method and salt
  # should always generate the same hashed_password.
  def password_match?(password="")
    hashed_password == AdminUser.hash_with_salt(password, salt)
  end
  
  def self.make_salt(username="")
    Digest::SHA1.hexdigest("Use #{username} with #{Time.now} to make salt")
  end
  
  def self.hash_with_salt(password="", salt="")
    Digest::SHA1.hexdigest("Put #{salt} on the #{password}")
  end
  
  private
  
  def create_hashed_password
    # Whenever :password has a value hashing is needed
    unless password.blank?
      # always use "self" when assigning values
      self.salt = AdminUser.make_salt(username) if salt.blank?
      self.hashed_password = AdminUser.hash_with_salt(password, salt)
    end
  end

  def clear_password
    # for security and b/c hashing is not needed
    self.password = nil
  end
  
end

app/models/client.rb
class Client < ActiveRecord::Base
  has_many :photos
end

app/models/contact.rb
class Contact < ActiveRecord::Base

  EMAIL_REGEX = /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}$/i
  
  validates :name, :presence => true, :length => { :maximum => 50 }
  validates :last_name, :presence => true, :length => { :maximum => 50 }
  validates :cell, :presence => true, :length => { :maximum => 20 }
  validates :office, :presence => true, :length => { :maximum => 20 }
  validates :email, :presence => true, :length => { :maximum => 100 }, 
    :format => EMAIL_REGEX
  validates :message, :presence => true, :length => { :maximum => 1000 }
  
end

app/models/howdowedo.rb
class Howdowedo < ActiveRecord::Base
  translates :title, :description
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :client
  has_attached_file :photo,
                    :styles => { :medium => "500x500#", :thumb => "50x50#" }
end

app/models/team.rb
class Team < ActiveRecord::Base
  translates :name, :description  
  validates_attachment_content_type :photo, :content_type => ["image/jpg", "image/jpeg", "image/png"]
  validates_attachment_size :photo, :less_than => 1.megabytes
  
  validates :name, :presence => true
  validates :description, :presence => true
  
  has_attached_file :photo, :styles => { :photo => ["160x220", :jpg] }
end

app/models/video.rb
class Video < ActiveRecord::Base
  auto_html_for :url do
      youtube(:width => 270, :height => 180)
      link :target => "_blank", :rel => "nofollow"
      simple_format
    end
end

app/models/whatdowedo.rb
class Whatdowedo < ActiveRecord::Base
  translates :title, :description
end

app/models/whoweare.rb
class Whoweare < ActiveRecord::Base
  translates :title, :description
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/photos_controller.rb
class PhotosController < InheritedResources::Base
  belongs_to :client
  def create
    create! { client_photos_path(@photo.client) }
  end
end

app/helpers/access_helper.rb
module AccessHelper
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/howdowedos_helper.rb
module HowdowedosHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/helpers/whatdowedos_helper.rb
module WhatdowedosHelper
end

app/helpers/whoweares_helper.rb
module WhowearesHelper
end

app/views/photos/_form.html.erb
<%= form_for(@photo, :html => { :multipart => true }, :url => { :action => 'create', :client_id => params[:client_id] }) do |f| %>
  <% if @photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% @photo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :photo, "Foto" %><br />
    <%= f.file_field :photo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/photos/edit.html.erb
<h1>Editing photo</h1>

<%= render 'form' %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

app/views/photos/index.html.erb
<h1>Fotos</h1>

<table>
  <tr>
    <th></th>
    <th></th>
  </tr>

<% @photos.each do |photo| %>
  <tr>
    <td><%= image_tag(photo.photo(:thumb)) %></td>
    <td><%= link_to 'Eliminar', client_photo_path(photo.client, photo), :confirm => '¿Estás seguro?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Nueva Foto', new_client_photo_path(params[:client_id]) %>
<%= link_to 'Atrás', clients_path %>

app/views/photos/new.html.erb
<h1>Nueva Foto</h1>

<%= render 'form' %>

<%= link_to 'Atrás', client_photos_path(params[:client_id]) %>

app/views/photos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Client:</b>
  <%= @photo.client_id %>
</p>


<%= link_to 'Edit', edit_photo_path(@photo) %> |
<%= link_to 'Back', photos_path %>