config/routes.rb
Contactocoaching::Application.routes.draw do

  scope '(:locale)', :locale => /#{I18n.available_locales.join("|")}/ do

    resources :videos
    resources :clients do
      resources :photos
    end
    resources :addresses
    resources :whoweares
    resources :howdowedos
    resources :teams
    resources :whatdowedos
    resources :contacts

    match 'quienes_somos' => 'whoweares#index'
    match "equipo" => "teams#index"
    match 'clientes' => 'clients#index'
    match 'videos' => 'videos#index'
    match 'como_lo_hacemos' => 'howdowedos#index'
    match 'que_hacemos' => 'whatdowedos#index'
    match 'contacto' => 'addresses#index'

    match "/admin" =>'access#index'
    match "/cms" =>'access#index'
    match "/login" =>'access#login'
    match "/attempt_login" =>'access#attempt_login'
    match "/logout" =>'access#logout'

    root :to => "home#index"

  end

end

app/models/address.rb
class Address < ActiveRecord::Base
  translates :title, :description
end

app/models/admin_user.rb
require 'digest/sha1'
class AdminUser < ActiveRecord::Base
  
  attr_accessor :password
  
  EMAIL_REGEX = /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}$/i
  
  # new "sexy" validations
  validates :first_name, :presence => true, :length => { :maximum => 25 }
  validates :last_name, :presence => true, :length => { :maximum => 50 }
  validates :username, :length => { :within => 8..25 }, :uniqueness => true
  validates :email, :presence => true, :length => { :maximum => 100 }, 
    :format => EMAIL_REGEX, :confirmation => true

  # only on create, so other attributes of this user can be changed
  validates_length_of :password, :within => 8..25, :on => :create

  before_save :create_hashed_password
  after_save :clear_password

  scope :named, lambda {|first,last| where(:first_name => first, :last_name => last)}
  scope :sorted, order("admin_users.last_name ASC, admin_users.first_name ASC")
  
  attr_protected :hashed_password, :salt
  
  def name
    "#{first_name} #{last_name}"
  end
  
  def self.authenticate(username="", password="")
    user = AdminUser.find_by_username(username)
    if user && user.password_match?(password)
      return user
    else
      return false
    end
  end

  # The same password string with the same hash method and salt
  # should always generate the same hashed_password.
  def password_match?(password="")
    hashed_password == AdminUser.hash_with_salt(password, salt)
  end
  
  def self.make_salt(username="")
    Digest::SHA1.hexdigest("Use #{username} with #{Time.now} to make salt")
  end
  
  def self.hash_with_salt(password="", salt="")
    Digest::SHA1.hexdigest("Put #{salt} on the #{password}")
  end
  
  private
  
  def create_hashed_password
    # Whenever :password has a value hashing is needed
    unless password.blank?
      # always use "self" when assigning values
      self.salt = AdminUser.make_salt(username) if salt.blank?
      self.hashed_password = AdminUser.hash_with_salt(password, salt)
    end
  end

  def clear_password
    # for security and b/c hashing is not needed
    self.password = nil
  end
  
end

app/models/client.rb
class Client < ActiveRecord::Base
  has_many :photos
end

app/models/contact.rb
class Contact < ActiveRecord::Base

  EMAIL_REGEX = /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}$/i
  
  validates :name, :presence => true, :length => { :maximum => 50 }
  validates :last_name, :presence => true, :length => { :maximum => 50 }
  validates :cell, :presence => true, :length => { :maximum => 20 }
  validates :office, :presence => true, :length => { :maximum => 20 }
  validates :email, :presence => true, :length => { :maximum => 100 }, 
    :format => EMAIL_REGEX
  validates :message, :presence => true, :length => { :maximum => 1000 }
  
end

app/models/howdowedo.rb
class Howdowedo < ActiveRecord::Base
  translates :title, :description
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :client
  has_attached_file :photo,
                    :styles => { :medium => "500x500#", :thumb => "50x50#" }
end

app/models/team.rb
class Team < ActiveRecord::Base
  translates :name, :description  
  validates_attachment_content_type :photo, :content_type => ["image/jpg", "image/jpeg", "image/png"]
  validates_attachment_size :photo, :less_than => 1.megabytes
  
  validates :name, :presence => true
  validates :description, :presence => true
  
  has_attached_file :photo, :styles => { :photo => ["160x220", :jpg] }
end

app/models/video.rb
class Video < ActiveRecord::Base
  auto_html_for :url do
      youtube(:width => 270, :height => 180)
      link :target => "_blank", :rel => "nofollow"
      simple_format
    end
end

app/models/whatdowedo.rb
class Whatdowedo < ActiveRecord::Base
  translates :title, :description
end

app/models/whoweare.rb
class Whoweare < ActiveRecord::Base
  translates :title, :description
end

app/helpers/access_helper.rb
module AccessHelper
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/howdowedos_helper.rb
module HowdowedosHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/helpers/whoweares_helper.rb
module WhowearesHelper
end

app/views/layouts/_menu-language.html.erb
<ul id="languages">
  <li>
    <%= link_to_unless I18n.locale == :en, "Inglés", url_for(:locale => 'en') do %>
      <span>Inglés</span>
    <% end %>
  </li>
  <li>
    <%= link_to_unless I18n.locale == :es, "Castellano", url_for(:locale => 'es') do %>
      <span>Castellano</span>
    <% end %>
  </li>
</ul>

app/views/layouts/_menu.html.erb
<ul id="menu">
            <li>
              <%= link_to_unless_current I18n.t('whoweare'), quienes_somos_path do %>
                <span><%= I18n.t('whoweare') %></span>
              <% end %>
            </li>
            <li>
	         <%= link_to_unless_current I18n.t('whatdowedo'), que_hacemos_path do %>
                <span><%= I18n.t('whatdowedo') %></span>
              <% end %>
            </li>
            <li>
	          <%= link_to_unless_current I18n.t('howdowedo'), como_lo_hacemos_path do %>
                <span><%= I18n.t('howdowedo') %></span>
              <% end %>
            </li>
            <li>
              <%= link_to_unless_current I18n.t('client'), clientes_path do %>
                <span><%= I18n.t('client') %></span>
              <% end %>
            </li>
            <li>
              <%= link_to_unless_current I18n.t('team'), equipo_path do %>
                <span><%= I18n.t('team') %></span>
              <% end %>
            </li>
            <li>
              <%= link_to_unless_current I18n.t('video'), videos_path do %>
                <span><%= I18n.t('video') %></span>
              <% end %>
            </li>
            <li>
              <%= link_to_unless_current I18n.t('address'), contacto_path do %>
                <span><%= I18n.t('address') %></span>
              <% end %>
            </li>
            <% if session[:user_id] %>
            <li>
	          <%= link_to 'Desconectarse', 'logout' %>
	        </li>
	        <% end %>

          </ul>

app/views/layouts/_metas.html.erb
  <meta name="description" content="Trabajamos mejorando la comunicación interna en las empresas, para que su equipo de trabajo funcione como un engranaje ajustado a la misión y visión de la empresa. Nuestro entrenamiento logra mejorar las relaciones interpersonales. Así como la relación de los trabajadores con los clientes." />
  <meta name="keywords" content="Coaching para empresas, talleres para empresas, estrategias de comunicación" />
  <meta name="robot" content="index,follow" />
  <meta name="copyright" content="Copyright &copy; <%= Time.now.year %> Contacto Coaching." />
  <meta name="author" content="Kosmyka.com" />
  <meta name="language" content="Spanish" />
  <meta name="revisit-after" content="1" />
  <meta name="googlebot" content="index,follow" />
  <meta name="city" content="Lima" />
  <meta name="country" content="Peru" />
  <meta name="state" content="Lima" />
  <meta name="zip code" content="Lima 4" />
  <meta name="subject" content="Contacto Coaching" />
  <meta name="geo.position" content="-9;-75" />
  <meta name="geo.country" content="PE" />
  <meta name="geo.region" content="PE-LIM" />

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= page_title %></title>

  <%= render 'layouts/metas' %>

  <%= stylesheet_link_tag '/adapt/1200.css' %>
  <%= stylesheet_link_tag '/javascripts/accordion/themes/base/jquery.ui.all.css', 'style.css' %>

  <%= javascript_include_tag '/javascripts/jquery.js', '/javascripts/jquery-ui.js', '/javascripts/jquery_ujs' %>
  <%= javascript_include_tag '/javascripts/accordion/ui/jquery.ui.core.js', '/javascripts/accordion/ui/jquery.ui.widget.js', '/javascripts/accordion/ui/jquery.ui.accordion.js' %>
  <%= javascript_include_tag 'application.js' %>
  <%= yield :javascript %>

  <%= favicon_link_tag "/favicon.png" %>
  <%= csrf_meta_tag %>



</head>
<body id="<%= body_id %>" class="<%= body_class %>">



<div id="container-bg1">
  <div id="container-bg2">

    <div class="container_12">
      <!-- START: sidebar-first -->
      <div id="sidebar-first" class="grid_4">
        <div id="header">
          <%= render 'layouts/menu' %>
          <%= link_to image_tag("logo.png"), root_path, :id => 'logo' %>

        </div>


     </div>
     <!-- END: sidebar-first -->

     <!-- START: sidebar-second -->
     <div id="sidebar-second" class="grid_7">
       <div id="preface-top">
         <%= render 'layouts/menu-language' %>
       </div>

       <div id="content" class="grid_6 prefix_1">
         <%= yield %>
       </div>
     </div>
     <!-- END: sidebar-second -->



    </div>
    <!-- END: container_12 -->


  </div>
</div>


<div id="footer">
  <div class="container_12">
     <div id="author">
       <a href="http://www.kosmyka.com" target="_blank"><span>Desarrollo web</span><img src="/images/kosmyka.png" /></a>
     </div>
  </div>
</div>

<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-21505372-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

</body>
</html>